[build]
builder = "dockerfile"
dockerfile = "Dockerfile.simple"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[experimental]
incrementalBuild = true 